name       : python-qtwebengine
version    : 5.15.2
release    : 10
source     :
    - https://pypi.python.org/packages/source/P/PyQtWebEngine/PyQtWebEngine-5.15.2.tar.gz : 4d72fea774071ce6f76e341a3d2c5d595886c9906a9b9493239c841cce54a634
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python bindings for QtWebEngine
description: |
    A set of Python bindings for the Qt Company's Qt WebEngine libraries.
replaces   :
    - python3-qtwebengine
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5WebEngine)
    - python3-qt5
    - python3-sip-devel
setup      : |
    python3 configure.py --no-sip-files
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir" -j1
