name       : python-qtwebengine
version    : 5.15.5
release    : 15
source     :
    - https://pypi.python.org/packages/source/P/PyQtWebEngine/PyQtWebEngine-5.15.5.tar.gz : ab47608dccf2b5e4b950d5a3cc704b17711af035024d07a9b71ad29fc103b941
homepage   : https://www.riverbankcomputing.com/software/pyqtwebengine
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python bindings for QtWebEngine
description: |
    A set of Python bindings for the Qt Company's Qt WebEngine libraries.
replaces   :
    - python3-qtwebengine
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(python3)
    - pyqt-builder
    - python-sip
    - python3-qt5
rundeps    :
    - python3-qt5
setup      : |
    sip-build \
        --no-make \
        --api-dir /usr/share/qt5/qsci/api/python
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT="$installdir"
